# Generated by Django 2.0.1 on 2018-01-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
