# Generated by Django 2.0.1 on 2018-01-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180125_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data',
            new_name='pub_data',
        ),
    ]
