# Generated by Django 2.0.1 on 2018-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180125_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pub_data',
        ),
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
