# Generated by Django 2.0.1 on 2018-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180124_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
