# Generated by Django 2.0.1 on 2018-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='addr',
            field=models.CharField(default=12, max_length=60),
            preserve_default=False,
        ),
    ]
